import Head from "next/head";
import Image from "next/image";
import { Inter } from "next/font/google";
import Layout from "@/components.js/Layout";
import profilePic from "/public/images/profile/HomeDark.png";
import profilePicDark from "/public/images/profile/Home.png";
import AnimatedText from "@/components.js/AnimatedText";
import Link from "next/link";
import { LinkArrow } from "@/components.js/Icons";
import HireMe from "@/components.js/HireMe";
import lightBulb from "/public/images/svgs/miscellaneous_icons_1.svg";
import Bulb1 from "/public/images/Bulb1.png";
import Bulb2 from "/public/images/Bulb2.png";
import Bulb1dark from "/public/images/Bulb1Dark.png";
import Bulb2dark from "/public/images/Bulb2Dark.png";
import Testimionals from "@/components.js/Testimonials.jsx";
import FAQSection from "@/components.js/FAQSection";
import TransitionEffect from "@/components.js/TransitionEffect";
import FeaturedProjects from "@/components.js/FeaturedProjects";

const inter = Inter({ subsets: ["latin"] });

export default function Home() {
  return (
    <>
      <Head>
        <title>Diago</title>
        <meta name="description" content="Generated by create next app" />
      </Head>
      <TransitionEffect />
      <main className="flex items-center text-dark w-full min-h-screen dark:text-light">
        <Layout className="pt-0 md:pt-16 sm:pt-8">
          <div className="flex items-center justify-between w-full lg:flex-col md:justify-between">
            <div className="w-1/2 md:w-full">
              {/* image */}
              <Image
                src={profilePic}
                alt="Diago"
                className="w-full h-auto dark:!hidden"
                priority
              />
              <Image
                src={profilePicDark}
                alt="Diago"
                className="w-full h-auto dark:inline-block hidden"
                priority
              />
            </div>

            {/* text */}
            <div className="w-1/2 flex flex-col items-center self-center lg:w-full lg:text-center">
              <AnimatedText
                text="Got an idea? We got the skill. Let's collaborate."
                className="!text-6xl !text-left xl:!text-5xl lg:!text-center lg:!text-6xl md:!text-5xl sm:!text-3xl"
              />

              {/* sub heading */}
              <p className="my-4 text-base font-medium md:text-sm sm:text-xs">
                As a talented video editor, I am passionate about transforming
                raw footage into captivating visual stories. I bring ideas to
                life through my expertise in editing techniques, color grading,
                and motion graphics. My latest projects and articles highlight
                my proficiency in video editing and my commitment to creating
                engaging and impactful content.
              </p>

              {/* two Buttons */}
              <div className="flex items-center self-start mt-2 lg:self-center">
                {/* Button 1 */}
                <Link
                  href="./projects"
                  className="flex items-center bg-dark text-light p-2.5 px-6 rounded-lg text-lg font-semibold hover:bg-light hover:text-dark border-2 border-solid border-transparent hover:border-dark dark:text-dark dark:bg-light dark:hover:text-light dark:hover:border-light dark:hover:bg-dark
                  md:p-2 md:text-base md:px-3"
                >
                  Projects <LinkArrow className={"w-6 ml-1"} />
                </Link>

                {/* Button 2 */}
                <Link
                  className="ml-4 text-lg font-medium capitalize text-dark underline dark:text-light md:text-base"
                  href="/contact"
                >
                  Conatct Me
                </Link>
              </div>
            </div>
          </div>

          {/* Featured Projects */}
          <FeaturedProjects/>

          {/* Testimionals */}
          <div>
            <Testimionals />
          </div>

          {/* Faq Section */}
          <div className="mt-16">
            <FAQSection />
          </div>
        </Layout>

        {/* Hire me Circular Component */}
        <HireMe />

        {/* Light Bulb */}
        <Link
          className="fixed right-14 bottom-8 inline-block w-24 group md:hidden"
          href="/contact"
        >
          <Image
            src={lightBulb}
            alt="Codebucks"
            className="w-full h-auto group-hover:glow group-hover:cursor-pointer"
          />
          <div className="absolute -right-16 bottom-10 inline-block w-80 invisible group-hover:visible">
            <Image
              src={Bulb1}
              className="h-auto absolute -bottom-8 -right-8 dark:hidden"
            />
            <Image
              src={Bulb1dark}
              className="h-auto absolute -bottom-8 -right-8 dark:block hidden"
            />
            <Image
              src={Bulb2}
              className="h-auto absolute -bottom-20 -right-8 dark:hidden"
            />
            <Image
              src={Bulb2dark}
              className="h-auto absolute -bottom-20 -right-8 dark:block hidden"
            />
          </div>
        </Link>
      </main>
    </>
  );
}
